name: beleg_speicher
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Lokalisierung für Material/Cupertino Widgets
  flutter_localizations:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  image_picker: ^0.8.7+4
  file_selector: ^0.9.0
  table_calendar: ^3.0.8
  intl: ^0.20.2
  flutter_secure_storage: ^8.0.0
  open_file: ^3.5.10
  share_plus: ^11.0.0
  file_picker: ^8.3.3
  path: ^1.8.3

  # Firebase Core + Auth + Storage + Firestore
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.1.0
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Pfeil_Back.png
    - assets/calendar_home.png
    - assets/folder_home.png
    - assets/time_home.png
    - assets/cloud_server.png
    - assets/google_logo.png
