// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKAqCrffWQK0GKP1O45hBTpJA0eyqYn0',
    appId: '1:264239207754:android:e8815085ee02d99b3d9db3',
    messagingSenderId: '264239207754',
    projectId: 'beleg-speicher',
    storageBucket: 'beleg-speicher.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqSDuMPv9JzAKHw1Tpm0DoHQhAvj_TZr0',
    appId: '1:264239207754:ios:8b3c68aecc0c0a643d9db3',
    messagingSenderId: '264239207754',
    projectId: 'beleg-speicher',
    storageBucket: 'beleg-speicher.firebasestorage.app',
    iosBundleId: 'beleg-speicher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqSDuMPv9JzAKHw1Tpm0DoHQhAvj_TZr0',
    appId: '1:264239207754:ios:313cc808cd3e8a203d9db3',
    messagingSenderId: '264239207754',
    projectId: 'beleg-speicher',
    storageBucket: 'beleg-speicher.firebasestorage.app',
    iosBundleId: 'com.example.belegSpeicher',
  );
}
